BTRS/Models/Login.cs
using System.ComponentModel.DataAnnotations;

namespace BTRS.Models
{
    public class Login
    {
        [Required(ErrorMessage = "Please fill the username")]
        public string Username { set; get; }
        [Required(ErrorMessage = "Please fill the password")]

        public string Password { set; get; }
    }
}

BTRS/Models/Passengers.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace BTRS.Models
{
	[Index(nameof(Passengers.Username), IsUnique = true)]
	[Index(nameof(Passengers.Email), IsUnique = true)]
	public class Passengers
	{
		[Key]
		public int Id { get; set; }
		[Required(ErrorMessage = "Enter passenger's name")]
		[StringLength(50)]
		public string Name { get; set; }
		[Required(ErrorMessage = "Enter passenger's username")]
		[StringLength(50)]
		public string Username { get; set; }
		[Required(ErrorMessage = "Enter passenger's password")]
		[StringLength(50)]
		public string Password { get; set; }
		[Required(ErrorMessage = "Enter passenger's E-mail")]
		[StringLength(50)]
		public string Email { get; set; }
		[Required(ErrorMessage = "Enter passenger's phone number")]
		public int PhoneNum { get; set; }
        [Required(ErrorMessage = "Enter passenger's Gender")]
        public string Gender { get; set; }

		public ICollection<Pass_Trips> Pass_Trips { get; set; }

	}
}

BTRS/Controllers/PassengersController.cs
using BTRS.DATA;
using BTRS.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace BTRS.Controllers
{
    public class PassengersController : Controller
    {

        private SystemDbContext _context;

        public PassengersController(SystemDbContext context)
        {
            this._context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SignUp(Passengers passengers)
        {
            bool empty = checkEmpty(passengers);
            bool duplicat = checkUsername(passengers.Name);
            bool duplicate = checkUsername(passengers.Username);


            if (empty)
            {
                if (duplicat)
                {
                    _context.passengers.Add(passengers);
                    _context.SaveChanges();

                    TempData["Msg"] = "the data was saved";
                    return View();
                }
                else
                {
                    TempData["Msg"] = "Please Change the username";
                    return View();
                }
            }
            else
            {
                TempData["Msg"] = "Please fill all input ";
                return View();
            }



        }

        private bool CheckEmpty(Passengers passengers)
        {
            throw new NotImplementedException();
        }

        private bool checkUsername(string username)
        {

            Passengers passengers = _context.passengers.Where(u => u.Username.Equals(username)).FirstOrDefault();
            if (passengers != null)
            {
                return false;
            }
            else
            {
                return true;
            }
        }
        public bool checkEmpty(Passengers passengers)
        {
            if (String.IsNullOrEmpty(passengers.Name)) return false;
            else if (String.IsNullOrEmpty(passengers.Username)) return false;
            else if (String.IsNullOrEmpty(passengers.Password)) return false;
            else if (String.IsNullOrEmpty(passengers.Email)) return false;
            else return true;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(Login passengerslogin)
        {
            if (ModelState.IsValid)
            {
                string username = passengerslogin.Username;
                string password = passengerslogin.Password;

                Passengers passengers = _context.passengers.Where(
                     p => p.Username.Equals(username) &&
                     p.Password.Equals(password)
                     ).FirstOrDefault();

                Admin admin = _context.admin.Where(
                    a => a.Username.Equals(username)
                    &&
                    a.Password.Equals(password)
                    ).FirstOrDefault();




                if (passengers != null)
                {
                    HttpContext.Session.SetInt32("PassengersId", passengers.Id);
                    return RedirectToAction("TripsList");
                }
                else if (admin != null)
                {

                    HttpContext.Session.SetInt32("adminID", admin.Id);

                    return RedirectToAction("Index", "Trips");
                }
                else
                {
                    TempData["Msg"] = "The user Not Found";
                }


            }
            else
            {

            }
            return View();
        }
        public IActionResult TripsList()
        {
            int PassengersId = (int)HttpContext.Session.GetInt32("PassengersId");

            List<int> lst=_context.pass_trips.Where(
                t => t.passengers.Id == PassengersId
                ).Select(s => s.trips.Id).ToList(); ;


            List<Trips> lst_trips=_context.trips.Where(
                t => lst.Contains(t.Id) == false
                ).ToList(); ;

            return View(lst_trips);
        }

        public IActionResult Booking(int id)
        {
            int PassengersId = (int)HttpContext.Session.GetInt32("PassengersId");

            Pass_Trips pass_Trips = new Pass_Trips();
            pass_Trips.passengers = _context.passengers.Find(PassengersId);
            pass_Trips.trips = _context.trips.Find(id);

            _context.pass_trips.Add(pass_Trips);
            _context.SaveChanges();

            return RedirectToAction("BookingList");
        }
        public IActionResult BookingList()
        {
            int PassengersId = (int)HttpContext.Session.GetInt32("PassengersId");

            List<int> lst_passengers = _context.pass_trips.Where(
                t => t.passengers.Id == PassengersId).Select(s => s.trips.Id).ToList();

            List<Trips> lst_trips = _context.trips.Where(
                t => lst_passengers.Contains(t.Id)
                ).ToList();

            return View(lst_trips);
        }

       public IActionResult Delete(int tripid)
        {
            int PassengersId = (int)HttpContext.Session.GetInt32("PassengersId");

             Pass_Trips pass_trips = _context.pass_trips.Where(
                t => t.passengers.Id == PassengersId && t.trips.Id==tripid
                ).FirstOrDefault();

            _context.pass_trips.Remove(pass_trips);
            _context.SaveChanges();
            return RedirectToAction("BookingList");
        }

    }
}

BTRS/Views/Passengers/BookingList.cshtml
@model IEnumerable<BTRS.Models.Trips>

@{
    ViewData["Title"] = "BookingList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>BookingList</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Destination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BusNum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Destination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BusNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
                <td>

                    <a asp-action="Delete" asp-route-tripid="@item.Id">Delete</a> |
                </td>
        </tr>
}
    </tbody>
</table>

BTRS/Views/Passengers/Login.cshtml
@model BTRS.Models.Passengers;

<form method="post">

    <table>
        <tr>
            <td>
                Username
            </td>
            <td>
                @Html.TextBox("Username")
                <span asp-validation-for="Username"></span>
            </td>

        </tr>

        <tr>
            <td>
                Password
            </td>
            <td>
                @Html.Password("Password")
                <span asp-validation-for="Password"></span>
            </td>

        </tr>

    </table>
    @Html.TextBox("LoginBtn", "Login", new { @type = "Submit" })
    <a asp-action="SignUp" asp-controller="Passengers" class="btn btn-link">  SignUp </a>

</form>

@TempData["Msg"]

BTRS/Views/Passengers/Signup.cshtml
@model BTRS.Models.Passengers;

<form method="post">

    <table>

        <tr>
            <td>
                Name
            </td>
            <td>
                @Html.TextBox("Name")
                <span asp-validation-for="Name"></span>
            </td>

        </tr>

        <tr>
            <td>
                Email
            </td>
            <td>
                @Html.TextBox("Email")
                <span asp-validation-for="Email"></span>
            </td>

        </tr>

        <tr>
            <td>
                PhoneNum
            </td>
            <td>
                @Html.TextBox("PhoneNum")
                <span asp-validation-for="PhoneNum"></span>
            </td>

        </tr>

        <tr>
            <td>
                Password
            </td>
            <td>
                @Html.TextBox("Password")
                <span asp-validation-for="Password"></span>
            </td>

        <tr>
            <td>
                Username
            </td>
            <td>
                    @Html.TextBox("Username")
                     <span asp-validation-for="Name"></span>
            </td>

        </tr>
        <tr>
            <td>
                Gender
            </td>
            <td>
                    @Html.TextBox("Gender")
                <span asp-validation-for="Gender"></span>
            </td>

        </tr>
    </table>
    @Html.TextBox("SignupBtn", "Signup", new { @type = "Submit" })

</form>

@TempData["Msg"]

BTRS/Views/Passengers/TripsList.cshtml
@model IEnumerable<BTRS.Models.Trips>

@{
    ViewData["Title"] = "TripsList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>TripsList</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Destination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BusNum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Destination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BusNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
                <td>
                    <a asp-action="Booking" asp-route-id="@item.Id">Booking</a> |
                </td>
        </tr>
}
    </tbody>
</table>