BTRS/Models/Trips.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BTRS.Models
{
	public class Trips
	{
		[Key]
        [Required(ErrorMessage = "Enter the Trip Id")]
        public int Id { get; set; }
		[Required(ErrorMessage = "Enter the destination")]
		[StringLength(100)]
		public string Destination { get; set; }
		[Required(ErrorMessage = "Enter the bus number")]
		public int BusNum { get; set; }
		[Required(ErrorMessage = "Enter the starting day")]
		public DateTime StartDate { get; set;}
		[Required(ErrorMessage = "Enter the ending day")]
		public DateTime EndDate { get; set;}

        [ForeignKey("AdminID")]
        public Admin Admin { get; set; }


    }
}

BTRS/Controllers/TripsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BTRS.DATA;
using BTRS.Models;

namespace BTRS.Controllers
{
    public class TripsController : Controller
    {
        private readonly SystemDbContext _context;

        public TripsController(SystemDbContext context)
        {
            _context = context;
        }

        // GET: Trips
        public ActionResult Index()
        {
            return View(_context.trips.ToList());
        }

        // GET: TripsContoller/Details/5
        public ActionResult Details(int id)
        {
            Trips trips = _context.trips.Find(id);

            return View(trips);
        }

        // GET: TripsContoller/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TripsContoller/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Trips trips)
        {
            try
            {

                int adminid = (int)HttpContext.Session.GetInt32("adminID");

                Admin admin = _context.admin.Where(
                  a => a.Id == adminid
                  ).FirstOrDefault();

                trips.Admin = admin;

                _context.trips.Add(trips);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TripsContoller/Edit/5
        public ActionResult Edit(int id)
        {
            Trips trips = _context.trips.Find(id);

            return View(trips);
        }

        // POST: TripsContoller/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Trips trips)
        {
            try
            {

                _context.trips.Update(trips);

                _context.SaveChanges();

                return RedirectToAction(nameof(Index));

            }
            catch
            {
                return View();
            }
        }

        // GET: TripsContoller/Delete/5
        public ActionResult Delete(int id)
        {
            Trips trips = _context.trips.Find(id);
            _context.trips.Remove(trips);
            _context.SaveChanges();

            return RedirectToAction("index");
        }

        // POST: TripsContoller/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Trips trips)
        {
            try
            {
                _context.trips.Remove(trips);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BTRS/Views/Trips/Create.cshtml
@model BTRS.Models.Trips

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Trips</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Trips">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BusNum" class="control-label"></label>
                <input asp-for="BusNum" class="form-control" />
                <span asp-validation-for="BusNum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BTRS/Views/Trips/Delete.cshtml
@model BTRS.Models.Trips

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trips</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BusNum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BusNum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BTRS/Views/Trips/Details.cshtml
@model BTRS.Models.Trips

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Trips</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BusNum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BusNum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BTRS/Views/Trips/Edit.cshtml
@model BTRS.Models.Trips

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Trips</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BusNum" class="control-label"></label>
                <input asp-for="BusNum" class="form-control" />
                <span asp-validation-for="BusNum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BTRS/Views/Trips/Index.cshtml
@model IEnumerable<BTRS.Models.Trips>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Destination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BusNum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Destination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BusNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>